/**
 * Parity pin for the `makeNameCategorizer` consolidation.
 *
 * `__fixtures__/nameCategorizer.parity.json` was generated by running the three
 * pre-consolidation categorizers (Cline, pi and ACP each carried their own copy
 * of the tokenizer and token table) over every string literal in their test
 * files plus edge cases — empty, whitespace, mixed case, camelCase, snake_case,
 * unicode, `mcp__x__y`, digits, over-length names. The shared factory must give
 * the identical answer for every one, per provider.
 */
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { categorizeClineToolName } from "../adapters/cline/permissionAdapter.js";
import { categorizePiToolName } from "../adapters/pi/permissionAdapter.js";
import { categorizeAcpToolName } from "../adapters/acp/permissionAdapter.js";

interface ParityCase {
  name: string;
  cline: string | null;
  pi: string | null;
  acp: string | null;
}

const cases: ParityCase[] = JSON.parse(readFileSync(new URL("./__fixtures__/nameCategorizer.parity.json", import.meta.url), "utf8"));

describe("makeNameCategorizer parity with the pre-consolidation categorizers", () => {
  it("covers a broad corpus, including names where the providers disagree", () => {
    expect(cases.length).toBeGreaterThan(200);
    expect(cases.some((c) => c.cline !== c.pi || c.pi !== c.acp)).toBe(true);
  });

  it.each(cases)("$name", ({ name, cline, pi, acp }) => {
    expect({ cline: categorizeClineToolName(name), pi: categorizePiToolName(name), acp: categorizeAcpToolName(name) }).toEqual({ cline, pi, acp });
  });
});
