/**
 * The built-in palette, verbatim from `frontend/src/index.css`.
 *
 * A stored theme overrides a subset of these; anything it does not define still
 * cascades from the stylesheet, so measuring a theme's contrast requires the
 * stylesheet's own values as the fallback layer. Derived entries (`var(...)`,
 * `color-mix(...)`) are kept as expressions, not flattened — they are the
 * mechanism by which a theme's primitives reach the chat-list and board layers.
 *
 * DO NOT EDIT BY HAND. `theme-contrast.stylesheet.test.ts` parses index.css and
 * asserts this map matches it key for key, in both modes.
 */
export const BUILTIN_PALETTE: { dark: Record<string, string>; light: Record<string, string> } = {
  dark: {
    accent: "#705ce0",
    "accent-bg": "rgba(99, 102, 241, 0.1)",
    "accent-hover": "#7562e6",
    "accent-light": "rgba(99, 102, 241, 0.1)",
    "accent-text": "color-mix(in srgb, var(--accent) 70%, white)",
    "assistant-bg": "#161b22",
    "badge-env-bg": "rgba(63, 185, 80, 0.12)",
    "badge-env-border": "#2d6a4f",
    "badge-env-text": "#3fb950",
    "badge-info": "#58a6ff",
    "badge-info-bg": "rgba(88, 166, 255, 0.15)",
    "badge-provider-codex-bg": "#047857",
    "badge-provider-acp-bg": "#1d4ed8",
    "badge-provider-openrouter-bg": "var(--badge-worktree)",
    "badge-provider-text": "var(--text-on-accent)",
    "badge-sse-bg": "rgba(29, 53, 87, 0.67)",
    "badge-sse-text": "#a8dadc",
    "badge-trigger": "#a78bfa",
    "badge-worktree": "#7c3aed",
    bg: "#0d1117",
    "bg-popout": "#1d2531",
    "bg-secondary": "#1c2128",
    "bg-sidebar": "#131920",
    "board-drawer-bg": "var(--bg)",
    "board-item-bg": "var(--surface)",
    "board-item-border": "var(--border)",
    "board-rollup-active": "var(--status-active)",
    "board-rollup-idle": "var(--text-muted)",
    "board-rollup-job-running": "var(--accent-text)",
    "board-rollup-needs-you": "var(--warning)",
    "board-section-label-text": "var(--text-muted)",
    "board-tile-bg": "var(--surface)",
    "board-tile-border": "var(--border)",
    "board-tile-meta-text": "var(--text-muted)",
    "board-tile-title-text": "var(--text)",
    "board-unread-dot": "var(--chatlist-unread-dot)",
    border: "#30363d",
    "border-light": "#21262d",
    "builtin-assistant-bg": "#1e293b",
    "builtin-assistant-border": "#60a5fa",
    "builtin-text": "#bfdbfe",
    "builtin-user-bg": "#1f2937",
    "builtin-user-border": "#60a5fa",
    "chatlist-badge-agent-bg": "color-mix(in srgb, var(--accent) 15%, transparent)",
    "chatlist-badge-agent-text": "var(--accent-text)",
    "chatlist-badge-session-cli-bg": "var(--status-active-solid)",
    "chatlist-badge-session-text": "var(--text-on-accent)",
    "chatlist-badge-session-web-bg": "var(--accent)",
    "chatlist-badge-status-bg": "color-mix(in srgb, var(--text-muted) 15%, transparent)",
    "chatlist-badge-status-text": "var(--text-muted)",
    "chatlist-badge-triggered-bg": "color-mix(in srgb, var(--status-triggered) 15%, transparent)",
    "chatlist-badge-triggered-text": "var(--status-triggered)",
    "chatlist-bookmark-icon": "var(--accent-text)",
    "chatlist-empty-text": "var(--text-muted)",
    "chatlist-header-bg": "transparent",
    "chatlist-header-border": "var(--border)",
    "chatlist-icon": "var(--text-muted)",
    "chatlist-icon-active": "var(--accent-text)",
    "chatlist-icon-delete": "var(--text-muted)",
    "chatlist-icon-nav": "var(--text)",
    "chatlist-icon-nav-active": "var(--text-on-accent)",
    "chatlist-item-active-bg": "var(--accent-light)",
    "chatlist-item-active-border": "var(--accent)",
    "chatlist-item-bg": "transparent",
    "chatlist-item-border": "var(--border)",
    "chatlist-item-hover-bg": "var(--surface)",
    "chatlist-item-path-text": "var(--text-muted)",
    "chatlist-item-time-text": "var(--text-muted)",
    "chatlist-item-title-text": "var(--text)",
    "chatlist-load-more-bg": "var(--surface)",
    "chatlist-load-more-border": "var(--border)",
    "chatlist-load-more-text": "var(--text)",
    "chatlist-subtitle-text": "var(--text-muted)",
    "chatlist-summon-bg": "color-mix(in srgb, var(--warning) 12%, transparent)",
    "chatlist-summon-text": "var(--warning)",
    "chatlist-summon-urgent-bg": "color-mix(in srgb, var(--danger) 12%, transparent)",
    "chatlist-summon-urgent-text": "var(--danger)",
    "chatlist-title-text": "var(--text)",
    "chatlist-tree-group-bg": "color-mix(in srgb, var(--accent) 4%, transparent)",
    "chatlist-tree-line": "var(--border)",
    "chatlist-unread-dot": "var(--accent)",
    "code-bg": "#0d1117",
    danger: "#f85149",
    "danger-bg": "rgba(248, 81, 73, 0.1)",
    "danger-border": "rgba(220, 53, 69, 0.4)",
    "danger-solid": "color-mix(in srgb, var(--danger) 75%, black)",
    "diff-added-bg": "rgba(46, 160, 67, 0.15)",
    "diff-added-border": "#2ea043",
    "diff-added-line-bg": "rgba(46, 160, 67, 0.1)",
    "diff-added-text": "#3fb950",
    "diff-hunk-bg": "rgba(112, 92, 224, 0.08)",
    "diff-removed-bg": "rgba(248, 81, 73, 0.15)",
    "diff-removed-border": "#f85149",
    "diff-removed-line-bg": "rgba(248, 81, 73, 0.1)",
    "diff-removed-text": "#ff7b72",
    error: "#f85149",
    "info-bg": "rgba(88, 166, 255, 0.1)",
    "overlay-bg": "rgba(0, 0, 0, 0.5)",
    "shadow-lg": "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
    "shadow-md": "0 4px 12px rgba(0, 0, 0, 0.15)",
    "shadow-sm": "0 1px 3px rgba(0, 0, 0, 0.2)",
    "status-active": "#10b981",
    "status-active-solid": "color-mix(in srgb, var(--status-active) 65%, black)",
    "status-green": "#22c55e",
    "status-triggered": "#f59e0b",
    success: "#3fb950",
    "success-bg": "rgba(63, 185, 80, 0.1)",
    surface: "#161b22",
    text: "#e6edf3",
    "text-muted": "#8b949e",
    "text-on-accent": "#ffffff",
    "text-on-danger": "#ffffff",
    "text-secondary": "#8b949e",
    "toggle-knob": "#ffffff",
    "user-bg": "#1a2332",
    warning: "#d29922",
    "warning-bg": "rgba(210, 153, 34, 0.15)",
  },
  light: {
    accent: "#705ce0",
    "accent-bg": "rgba(112, 92, 224, 0.08)",
    "accent-hover": "#7562e6",
    "accent-light": "rgba(112, 92, 224, 0.08)",
    "accent-text": "color-mix(in srgb, var(--accent) 80%, black)",
    "assistant-bg": "#f8fafc",
    "badge-env-bg": "rgba(22, 163, 106, 0.1)",
    "badge-env-border": "#16a34a",
    "badge-env-text": "#166534",
    "badge-info": "#1d4ed8",
    "badge-info-bg": "rgba(37, 99, 235, 0.1)",
    "badge-provider-codex-bg": "#047857",
    "badge-provider-acp-bg": "#1d4ed8",
    "badge-provider-openrouter-bg": "var(--badge-worktree)",
    "badge-provider-text": "var(--text-on-accent)",
    "badge-sse-bg": "rgba(29, 78, 216, 0.1)",
    "badge-sse-text": "#1d4ed8",
    "badge-trigger": "#7c3aed",
    "badge-worktree": "#7c3aed",
    bg: "#ffffff",
    "bg-popout": "#fdfeff",
    "bg-secondary": "#f0f4f8",
    "bg-sidebar": "#eef1f6",
    "board-drawer-bg": "var(--bg)",
    "board-item-bg": "var(--surface)",
    "board-item-border": "var(--border)",
    "board-rollup-active": "var(--status-active)",
    "board-rollup-idle": "var(--text-muted)",
    "board-rollup-job-running": "var(--accent-text)",
    "board-rollup-needs-you": "var(--warning)",
    "board-section-label-text": "var(--text-muted)",
    "board-tile-bg": "var(--surface)",
    "board-tile-border": "var(--border)",
    "board-tile-meta-text": "var(--text-muted)",
    "board-tile-title-text": "var(--text)",
    "board-unread-dot": "var(--chatlist-unread-dot)",
    border: "#e2e8f0",
    "border-light": "#e2e8f0",
    "builtin-assistant-bg": "#eff6ff",
    "builtin-assistant-border": "#3b82f6",
    "builtin-text": "#1e40af",
    "builtin-user-bg": "#dbeafe",
    "builtin-user-border": "#3b82f6",
    "chatlist-badge-agent-bg": "color-mix(in srgb, var(--accent) 15%, transparent)",
    "chatlist-badge-agent-text": "var(--accent-text)",
    "chatlist-badge-session-cli-bg": "var(--status-active-solid)",
    "chatlist-badge-session-text": "var(--text-on-accent)",
    "chatlist-badge-session-web-bg": "var(--accent)",
    "chatlist-badge-status-bg": "color-mix(in srgb, var(--text-muted) 15%, transparent)",
    "chatlist-badge-status-text": "var(--text-muted)",
    "chatlist-badge-triggered-bg": "color-mix(in srgb, var(--status-triggered) 15%, transparent)",
    "chatlist-badge-triggered-text": "var(--status-triggered)",
    "chatlist-bookmark-icon": "var(--accent-text)",
    "chatlist-empty-text": "var(--text-muted)",
    "chatlist-header-bg": "transparent",
    "chatlist-header-border": "var(--border)",
    "chatlist-icon": "var(--text-muted)",
    "chatlist-icon-active": "var(--accent-text)",
    "chatlist-icon-delete": "var(--text-muted)",
    "chatlist-icon-nav": "var(--text)",
    "chatlist-icon-nav-active": "var(--text-on-accent)",
    "chatlist-item-active-bg": "var(--accent-light)",
    "chatlist-item-active-border": "var(--accent)",
    "chatlist-item-bg": "transparent",
    "chatlist-item-border": "var(--border)",
    "chatlist-item-hover-bg": "var(--surface)",
    "chatlist-item-path-text": "var(--text-muted)",
    "chatlist-item-time-text": "var(--text-muted)",
    "chatlist-item-title-text": "var(--text)",
    "chatlist-load-more-bg": "var(--surface)",
    "chatlist-load-more-border": "var(--border)",
    "chatlist-load-more-text": "var(--text)",
    "chatlist-subtitle-text": "var(--text-muted)",
    "chatlist-summon-bg": "color-mix(in srgb, var(--warning) 12%, transparent)",
    "chatlist-summon-text": "var(--warning)",
    "chatlist-summon-urgent-bg": "color-mix(in srgb, var(--danger) 12%, transparent)",
    "chatlist-summon-urgent-text": "var(--danger)",
    "chatlist-title-text": "var(--text)",
    "chatlist-tree-group-bg": "color-mix(in srgb, var(--accent) 4%, transparent)",
    "chatlist-tree-line": "var(--border)",
    "chatlist-unread-dot": "var(--accent)",
    "code-bg": "#f1f5f9",
    danger: "#b91c1c",
    "danger-bg": "rgba(185, 28, 28, 0.08)",
    "danger-border": "rgba(185, 28, 28, 0.3)",
    "danger-solid": "var(--danger)",
    "diff-added-bg": "rgba(46, 160, 67, 0.12)",
    "diff-added-border": "#1a7f37",
    "diff-added-line-bg": "rgba(46, 160, 67, 0.08)",
    "diff-added-text": "#166534",
    "diff-hunk-bg": "rgba(112, 92, 224, 0.06)",
    "diff-removed-bg": "rgba(248, 81, 73, 0.12)",
    "diff-removed-border": "#cf222e",
    "diff-removed-line-bg": "rgba(248, 81, 73, 0.08)",
    "diff-removed-text": "#b91c1c",
    error: "#cf222e",
    "info-bg": "rgba(37, 99, 235, 0.08)",
    "overlay-bg": "rgba(0, 0, 0, 0.3)",
    "shadow-lg": "0 20px 25px -5px rgba(0, 0, 0, 0.08), 0 10px 10px -5px rgba(0, 0, 0, 0.03)",
    "shadow-md": "0 4px 12px rgba(0, 0, 0, 0.1)",
    "shadow-sm": "0 1px 3px rgba(0, 0, 0, 0.1)",
    "status-active": "#047857",
    "status-active-solid": "var(--status-active)",
    "status-green": "#15803d",
    "status-triggered": "#92400e",
    success: "#166534",
    "success-bg": "rgba(22, 163, 106, 0.08)",
    surface: "#f8fafc",
    text: "#1e293b",
    "text-muted": "#556070",
    "text-on-accent": "#ffffff",
    "text-on-danger": "#ffffff",
    "text-secondary": "#556070",
    "toggle-knob": "#ffffff",
    "user-bg": "#e0e7ff",
    warning: "#854d0e",
    "warning-bg": "rgba(133, 77, 14, 0.1)",
  },
};
